Repository 24pullrequests/24pullrequests, pull requests merged in 2018-11, with the labels that each got.

#2365 Added rake tasks to reset user and org pull requests counts
  lib/tasks/organisations.rake
  lib/tasks/pull_requests.rake
Labels: misc

#2366 Add octobox to sponsor page and update links to be https
  app/assets/images/sponsors/libraries.png
  app/assets/images/sponsors/octobox.png
  app/views/application/_footer.html.erb
  app/views/static/sponsors.html.erb
Labels: misc

#2368 Use "Contributors" instead of "Developers" across the site
  Readme.md
  app/views/application/_finished.html.erb
  app/views/application/_header.html.erb
  app/views/application/_information.html.erb
  app/views/languages/show.html.erb
  app/views/reminder_mailer/november.html.erb
  app/views/reminder_mailer/november.text.erb
  app/views/static/homepage.html.erb
  app/views/users/index.html.erb
  config/locales/cs.yml
  config/locales/de.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/hi.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/nb.yml
  config/locales/pt_br.yml
  config/locales/ru.yml
  config/locales/ta.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/locales/zh_Hans.yml
  config/locales/zh_Hant.yml
  spec/requests/languages_spec.rb
  spec/requests/static_pages_spec.rb
  spec/requests/users_spec.rb
Labels: enhancement

#2370 Switch to travis virtual machine-based runtime
  .travis.yml
Labels: misc

#2373 Remove geocoder as it's no longer used
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/maps.js
  app/models/user.rb
  config/initializers/geocoder.rb
  lib/tasks/add_user_location.rake
  spec/support/geocoder.rb
  vendor/assets/javascripts/polyfills.js
Labels: refactoring

#2375 Clean up about
  app/views/static/about.html.erb
  app/views/static/sponsors.html.erb
  config/locales/cs.yml
  config/locales/de.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/hi.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/nb.yml
  config/locales/pt_br.yml
  config/locales/ru.yml
  config/locales/ta.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/locales/zh_Hans.yml
  config/locales/zh_Hant.yml
  config/routes.rb
Labels: visual design

#2379 Move toward 24prs
  app/assets/images/tagline.png
  design/tagline.sketch
Labels: visual design

#2385 Clear padding on container-fluid to fix darker bar accross the top
  app/assets/stylesheets/site.scss
Labels: bug

#2387 Automatically run migrations on heroku deploys
  Procfile
Labels: misc

#2391 Remove unused methods from the static controller
  app/controllers/static_controller.rb
Labels: refactoring

#2392 Landing page for 2018
  app/views/contributions/_form.html.erb
  app/views/contributions/new.html.erb
  app/views/dashboards/show.html.erb
  app/views/static/2018.html.erb
  app/views/static/homepage.html.erb
  config/routes.rb
Labels: enhancement

#2397 Tweaks to the 2018 page
  app/views/static/2018.html.erb
Labels: documentation
